In [1]:
import json
import pandas as pd

In [32]:
with open("../data/raw/variant_13/raw_20260311_175933.json", "r") as f:
    data = json.load(f)

In [9]:
type(data)

list

In [10]:
len(data)

2

In [11]:
type(data[1])

list

In [13]:
len(data[1])

66

In [16]:
records = data[1]

In [17]:
df = pd.json_normalize(records)

In [28]:
df.head()

   country_name countryiso3code       date   value
0  South Africa             ZAF 2025-01-01  32.391
1  South Africa             ZAF 2024-01-01  32.279
2  South Africa             ZAF 2023-01-01  32.098
3  South Africa             ZAF 2022-01-01  33.268
4  South Africa             ZAF 2021-01-01  34.007

In [20]:
df.dtypes

countryiso3code        str
date                   str
value              float64
unit                   str
obs_status             str
decimal              int64
indicator.id           str
indicator.value        str
country.id             str
country.value          str
dtype: object

In [21]:
df.shape

(66, 10)

In [22]:
df = df.rename(columns={
    "indicator.id": "indicator_id",
    "indicator.value": "indicator_name",
    "country.id": "country_id",
    "country.value": "country_name"
})

In [23]:
df["date"] = pd.to_datetime(df["date"], format="%Y")

In [24]:
df["value"] = pd.to_numeric(df["value"])

In [25]:
df = df[[
    "country_name",
    "countryiso3code",
    "date",
    "value"
]]

In [26]:
df = df.dropna()
df = df.drop_duplicates()

In [27]:
df.head()

   country_name countryiso3code       date   value
0  South Africa             ZAF 2025-01-01  32.391
1  South Africa             ZAF 2024-01-01  32.279
2  South Africa             ZAF 2023-01-01  32.098
3  South Africa             ZAF 2022-01-01  33.268
4  South Africa             ZAF 2021-01-01  34.007

In [29]:
df.dtypes

country_name                  str
countryiso3code               str
date               datetime64[us]
value                     float64
dtype: object

In [30]:
df.isna().sum()

country_name       0
countryiso3code    0
date               0
value              0
dtype: int64

In [36]:
df.to_csv(
    "../data/normalized/variant_13/2026-03-23_12-00-00.csv",
    index=False
)